(function () {
  'use strict';
  window.DC = window.DC || {};

  /** @typedef {{id:string, rank:number, name:string, team:string, position:string, byeWeek:number}} Player */

  function slug(name, team) {
    return (name + '-' + team).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  }

  /** @type {Object<string, number>} 2025 bye weeks, plausible — user imports real data later */
  var TEAM_BYE_WEEKS = {
    ARI: 5, ATL: 5, BAL: 5, BUF: 5,
    CAR: 6, CHI: 6, CIN: 6,
    CLE: 7, DAL: 7, DEN: 7,
    DET: 8, GB: 8, HOU: 8, IND: 8,
    JAX: 9, KC: 9, LAC: 9,
    LAR: 10, LV: 10, MIA: 10,
    MIN: 11, NE: 11, NO: 11,
    NYG: 12, NYJ: 12, PHI: 12,
    PIT: 13, SEA: 13, SF: 13,
    TB: 14, TEN: 14, WAS: 14
  };

  // raw ranked tuples [name, team, position]; array order = overall rank (index+1)
  var RAW_PLAYERS = [
    // 1-11: elite WR anchors
    ["Ja'Marr Chase", 'CIN', 'WR'],
    ['Justin Jefferson', 'MIN', 'WR'],
    ['CeeDee Lamb', 'DAL', 'WR'],
    ['Amon-Ra St. Brown', 'DET', 'WR'],
    ['Puka Nacua', 'LAR', 'WR'],
    ['Malik Nabers', 'NYG', 'WR'],
    ['Nico Collins', 'HOU', 'WR'],
    ['Brian Thomas Jr', 'JAX', 'WR'],
    ['A.J. Brown', 'PHI', 'WR'],
    ['Tyreek Hill', 'MIA', 'WR'],
    ['Ladd McConkey', 'LAC', 'WR'],
    // 12-19: elite RB anchors
    ['Bijan Robinson', 'ATL', 'RB'],
    ['Saquon Barkley', 'PHI', 'RB'],
    ['Jahmyr Gibbs', 'DET', 'RB'],
    ['Christian McCaffrey', 'SF', 'RB'],
    ['Ashton Jeanty', 'LV', 'RB'],
    ["De'Von Achane", 'MIA', 'RB'],
    ['Derrick Henry', 'BAL', 'RB'],
    ['Jonathan Taylor', 'IND', 'RB'],
    // 20-27: elite QB/TE cluster begins
    ['Josh Allen', 'BUF', 'QB'],
    ['Brock Bowers', 'LV', 'TE'],
    ['Lamar Jackson', 'BAL', 'QB'],
    ['Jalen Hurts', 'PHI', 'QB'],
    ['Jayden Daniels', 'WAS', 'QB'],
    ['Joe Burrow', 'CIN', 'QB'],
    ['Trey McBride', 'ARI', 'TE'],
    ['George Kittle', 'SF', 'TE'],
    // 28-29: RB depth begins (top ~30 exempt from the position-run-length guard below)
    ['Kyren Williams', 'LAR', 'RB'],
    ['Bucky Irving', 'TB', 'RB'],
    // 30-252: cross-position interleave (RB2/3s, WR3/4s, mid QBs, TE2s mixed;
    // QB/TE tails and rookie/handcuff RBs and deep WRs stretch into the 150-250 range)
    ['Patrick Mahomes', 'KC', 'QB'],
    ['Drake London', 'ATL', 'WR'],
    ['Chase Brown', 'CIN', 'RB'],
    ['DK Metcalf', 'PIT', 'WR'],
    ['DeVonta Smith', 'PHI', 'WR'],
    ['James Cook', 'BUF', 'RB'],
    ['Sam LaPorta', 'DET', 'TE'],
    ['Jared Goff', 'DET', 'QB'],
    ['Baker Mayfield', 'TB', 'QB'],
    ['Garrett Wilson', 'NYJ', 'WR'],
    ['T.J. Hockenson', 'MIN', 'TE'],
    ['Marvin Harrison Jr', 'ARI', 'WR'],
    ['Breece Hall', 'NYJ', 'RB'],
    ['Bo Nix', 'DEN', 'QB'],
    ['Rome Odunze', 'CHI', 'WR'],
    ['C.J. Stroud', 'HOU', 'QB'],
    ['Xavier Worthy', 'KC', 'WR'],
    ['Kyler Murray', 'ARI', 'QB'],
    ['Josh Jacobs', 'GB', 'RB'],
    ['Jaxon Smith-Njigba', 'SEA', 'WR'],
    ['Terry McLaurin', 'WAS', 'WR'],
    ['Kenneth Walker III', 'SEA', 'RB'],
    ['Zay Flowers', 'BAL', 'WR'],
    ['Courtland Sutton', 'DEN', 'WR'],
    ['Alvin Kamara', 'NO', 'RB'],
    ['Evan Engram', 'DEN', 'TE'],
    ['Aaron Jones', 'MIN', 'RB'],
    ['Jameson Williams', 'DET', 'WR'],
    ['Tee Higgins', 'CIN', 'WR'],
    ['Chris Godwin', 'TB', 'WR'],
    ['Tony Pollard', 'TEN', 'RB'],
    ['Omarion Hampton', 'LAC', 'RB'],
    ['Joe Mixon', 'HOU', 'RB'],
    ['Rashee Rice', 'KC', 'WR'],
    ['Travis Etienne Jr', 'JAX', 'RB'],
    ['Brock Purdy', 'SF', 'QB'],
    ['James Conner', 'ARI', 'RB'],
    ['Deebo Samuel', 'WAS', 'WR'],
    ['Kyle Pitts', 'ATL', 'TE'],
    ['Justin Herbert', 'LAC', 'QB'],
    ['Stefon Diggs', 'NE', 'WR'],
    ['Chuba Hubbard', 'CAR', 'RB'],
    ["D'Andre Swift", 'CHI', 'RB'],
    ['Keenan Allen', 'LAC', 'WR'],
    ['David Njoku', 'CLE', 'TE'],
    ['Michael Wilson', 'ARI', 'WR'],
    ['Greg Dortch', 'ARI', 'WR'],
    ['Dak Prescott', 'DAL', 'QB'],
    ['Quinshon Judkins', 'CLE', 'RB'],
    ['Javonte Williams', 'DAL', 'RB'],
    ['Matthew Stafford', 'LAR', 'QB'],
    ['Zay Jones', 'ARI', 'WR'],
    ['Dallas Goedert', 'PHI', 'TE'],
    ['Darnell Mooney', 'ATL', 'WR'],
    ['Trevor Lawrence', 'JAX', 'QB'],
    ['Ray-Ray McCloud', 'ATL', 'WR'],
    ['RJ Harvey', 'DEN', 'RB'],
    ['KhaDarel Hodge', 'ATL', 'WR'],
    ['Rashod Bateman', 'BAL', 'WR'],
    ['Nelson Agholor', 'BAL', 'WR'],
    ['Isiah Pacheco', 'KC', 'RB'],
    ['Tylan Wallace', 'BAL', 'WR'],
    ['TreVeyon Henderson', 'NE', 'RB'],
    ['Tyrone Tracy Jr', 'NYG', 'RB'],
    ['Jaylen Warren', 'PIT', 'RB'],
    ['Justin Fields', 'NYJ', 'QB'],
    ['Khalil Shakir', 'BUF', 'WR'],
    ['Brian Robinson Jr', 'WAS', 'RB'],
    ['Sam Darnold', 'SEA', 'QB'],
    ['Curtis Samuel', 'BUF', 'WR'],
    ['Keon Coleman', 'BUF', 'WR'],
    ['Geno Smith', 'LV', 'QB'],
    ['Mark Andrews', 'BAL', 'TE'],
    ['Rhamondre Stevenson', 'NE', 'RB'],
    ['Zach Charbonnet', 'SEA', 'RB'],
    ['Joshua Palmer', 'BUF', 'WR'],
    ['Najee Harris', 'LAC', 'RB'],
    ['Jake Ferguson', 'DAL', 'TE'],
    ['Tetairoa McMillan', 'CAR', 'WR'],
    ['Xavier Legette', 'CAR', 'WR'],
    ['Jalen Coker', 'CAR', 'WR'],
    ['Rachaad White', 'TB', 'RB'],
    ['Adam Thielen', 'CAR', 'WR'],
    ['DJ Moore', 'CHI', 'WR'],
    ['Colby Parkinson', 'LAR', 'TE'],
    ['Luther Burden III', 'CHI', 'WR'],
    ['Tank Bigsby', 'JAX', 'RB'],
    ['Olamide Zaccheaus', 'CHI', 'WR'],
    ['Andrei Iosivas', 'CIN', 'WR'],
    ['Jermaine Burton', 'CIN', 'WR'],
    ['Caleb Williams', 'CHI', 'QB'],
    ['Jerry Jeudy', 'CLE', 'WR'],
    ['Jaylen Wright', 'MIA', 'RB'],
    ['Cedric Tillman', 'CLE', 'WR'],
    ['Drake Maye', 'NE', 'QB'],
    ['Braelon Allen', 'NYJ', 'RB'],
    ['Dalton Kincaid', 'BUF', 'TE'],
    ['Tucker Kraft', 'GB', 'TE'],
    ['Elijah Moore', 'CLE', 'WR'],
    ['Ray Davis', 'BUF', 'RB'],
    ['David Bell', 'CLE', 'WR'],
    ['George Pickens', 'DAL', 'WR'],
    ['Justice Hill', 'BAL', 'RB'],
    ['Jalen Tolbert', 'DAL', 'WR'],
    ['KaVontae Turpin', 'DAL', 'WR'],
    ['Trey Benson', 'ARI', 'RB'],
    ['Marvin Mims Jr', 'DEN', 'WR'],
    ['Troy Franklin', 'DEN', 'WR'],
    ['Pat Bryant', 'DEN', 'WR'],
    ['Ty Chandler', 'MIN', 'RB'],
    ['Tim Patrick', 'DET', 'WR'],
    ['Isaac TeSlaa', 'DET', 'WR'],
    ['Jayden Reed', 'GB', 'WR'],
    ['Blake Corum', 'LAR', 'RB'],
    ['Romeo Doubs', 'GB', 'WR'],
    ['J.J. McCarthy', 'MIN', 'QB'],
    ['Nick Chubb', 'HOU', 'RB'],
    ['Matthew Golden', 'GB', 'WR'],
    ['Dontayvion Wicks', 'GB', 'WR'],
    ['Tank Dell', 'HOU', 'WR'],
    ['Michael Penix Jr', 'ATL', 'QB'],
    ['Christian Kirk', 'HOU', 'WR'],
    ['Jayden Higgins', 'HOU', 'WR'],
    ['Josh Downs', 'IND', 'WR'],
    ['Cole Kmet', 'CHI', 'TE'],
    ['Jerome Ford', 'CLE', 'RB'],
    ['Michael Pittman Jr', 'IND', 'WR'],
    ['Alec Pierce', 'IND', 'WR'],
    ['Adonai Mitchell', 'IND', 'WR'],
    ['Pat Freiermuth', 'PIT', 'TE'],
    ['Travis Hunter', 'JAX', 'WR'],
    ['Devin Singletary', 'NYG', 'RB'],
    ['Parker Washington', 'JAX', 'WR'],
    ['Dyami Brown', 'JAX', 'WR'],
    ['Hunter Henry', 'NE', 'TE'],
    ['Bryce Young', 'CAR', 'QB'],
    ['Roschon Johnson', 'CHI', 'RB'],
    ['Hollywood Brown', 'KC', 'WR'],
    ['Tyler Warren', 'IND', 'TE'],
    ['Anthony Richardson', 'IND', 'QB'],
    ['Tua Tagovailoa', 'MIA', 'QB'],
    ['JuJu Smith-Schuster', 'KC', 'WR'],
    ['Antonio Gibson', 'NE', 'RB'],
    ['Zach Ertz', 'WAS', 'TE'],
    ['Quentin Johnston', 'LAC', 'WR'],
    ['Tre Harris', 'LAC', 'WR'],
    ['Davante Adams', 'LAR', 'WR'],
    ['Chris Rodriguez', 'WAS', 'RB'],
    ['Aaron Rodgers', 'PIT', 'QB'],
    ['Sean Tucker', 'TB', 'RB'],
    ['Emari Demercado', 'ARI', 'RB'],
    ['Tutu Atwell', 'LAR', 'WR'],
    ['Jordan Whittington', 'LAR', 'WR'],
    ['Cade Otton', 'TB', 'TE'],
    ['Jakobi Meyers', 'LV', 'WR'],
    ['Tre Tucker', 'LV', 'WR'],
    ["Dont'e Thornton Jr", 'LV', 'WR'],
    ['Russell Wilson', 'NYG', 'QB'],
    ['Jack Bech', 'LV', 'WR'],
    ['Jaylen Waddle', 'MIA', 'WR'],
    ['Malik Washington', 'MIA', 'WR'],
    ['Isaac Guerendo', 'SF', 'RB'],
    ['Nick Westbrook-Ikhine', 'MIA', 'WR'],
    ['Jordan Addison', 'MIN', 'WR'],
    ['Chig Okonkwo', 'TEN', 'TE'],
    ['Jalen Nailor', 'MIN', 'WR'],
    ['Jordan Love', 'GB', 'QB'],
    ['Juwan Johnson', 'NO', 'TE'],
    ['Kendre Miller', 'NO', 'RB'],
    ['Rondale Moore', 'MIN', 'WR'],
    ['DeMario Douglas', 'NE', 'WR'],
    ['Kayshon Boutte', 'NE', 'WR'],
    ['Isaiah Likely', 'BAL', 'TE'],
    ['Kyle Williams', 'NE', 'WR'],
    ['Chris Olave', 'NO', 'WR'],
    ['Bhayshul Tuten', 'JAX', 'RB'],
    ['Rashid Shaheed', 'NO', 'WR'],
    ['Cam Ward', 'TEN', 'QB'],
    ['Brandin Cooks', 'NO', 'WR'],
    ['Devaughn Vele', 'NO', 'WR'],
    ['Elijah Arroyo', 'SEA', 'TE'],
    ["Wan'Dale Robinson", 'NYG', 'WR'],
    ['Kenny Pickett', 'CLE', 'QB'],
    ['Darius Slayton', 'NYG', 'WR'],
    ['Jalin Hyatt', 'NYG', 'WR'],
    ['MarShawn Lloyd', 'GB', 'RB'],
    ['Josh Reynolds', 'NYJ', 'WR'],
    ['Allen Lazard', 'NYJ', 'WR'],
    ['Xavier Gipson', 'NYJ', 'WR'],
    ['Kimani Vidal', 'LAC', 'RB'],
    ['Dylan Sampson', 'CLE', 'RB'],
    ['Jahan Dotson', 'PHI', 'WR'],
    ['Woody Marks', 'HOU', 'RB'],
    ['Johnny Wilson', 'PHI', 'WR'],
    ['Calvin Austin III', 'PIT', 'WR'],
    ['Roman Wilson', 'PIT', 'WR'],
    ['Harold Fannin Jr', 'CLE', 'TE'],
    ['Ben Skowronek', 'PIT', 'WR'],
    ['Mason Taylor', 'NYJ', 'TE'],
    ['Cooper Kupp', 'SEA', 'WR'],
    ['Tory Horton', 'SEA', 'WR'],
    ['Marquez Valdes-Scantling', 'SEA', 'WR'],
    ['Cam Skattebo', 'NYG', 'RB'],
    ['Brandon Aiyuk', 'SF', 'WR'],
    ['Jauan Jennings', 'SF', 'WR'],
    ['Ricky Pearsall', 'SF', 'WR'],
    ['Spencer Rattler', 'NO', 'QB'],
    ['Demarcus Robinson', 'SF', 'WR'],
    ['DJ Giddens', 'IND', 'RB'],
    ['Mike Evans', 'TB', 'WR'],
    ['Jaydon Blue', 'DAL', 'RB'],
    ['Brenton Strange', 'JAX', 'TE'],
    ['Emeka Egbuka', 'TB', 'WR'],
    ['Kaleb Johnson', 'PIT', 'RB'],
    ['Jalen McMillan', 'TB', 'WR'],
    ['Tyler Allgeier', 'ATL', 'RB'],
    ['Calvin Ridley', 'TEN', 'WR'],
    ['Elic Ayomanor', 'TEN', 'WR'],
    ['Tyler Lockett', 'TEN', 'WR'],
    ['Theo Johnson', 'NYG', 'TE'],
    ['Van Jefferson', 'TEN', 'WR'],
    ['Noah Brown', 'WAS', 'WR'],
    ['Jaylin Lane', 'WAS', 'WR'],
    // 253-276: kickers + team defenses, interleaved in blocks of 6 (run-length guard: max 7)
    ['Justin Tucker', 'BAL', 'K'],
    ['Harrison Butker', 'KC', 'K'],
    ['Brandon Aubrey', 'DAL', 'K'],
    ['Jake Bates', 'DET', 'K'],
    ['Cameron Dicker', 'LAC', 'K'],
    ['Chris Boswell', 'PIT', 'K'],
    ['49ers D/ST', 'SF', 'DST'],
    ['Broncos D/ST', 'DEN', 'DST'],
    ['Ravens D/ST', 'BAL', 'DST'],
    ['Steelers D/ST', 'PIT', 'DST'],
    ['Cowboys D/ST', 'DAL', 'DST'],
    ['Eagles D/ST', 'PHI', 'DST'],
    ['Younghoe Koo', 'ATL', 'K'],
    ['Tyler Bass', 'BUF', 'K'],
    ['Jason Sanders', 'MIA', 'K'],
    ["Ka'imi Fairbairn", 'HOU', 'K'],
    ['Evan McPherson', 'CIN', 'K'],
    ['Joshua Karty', 'LAR', 'K'],
    ['Texans D/ST', 'HOU', 'DST'],
    ['Packers D/ST', 'GB', 'DST'],
    ['Jets D/ST', 'NYJ', 'DST'],
    ['Vikings D/ST', 'MIN', 'DST'],
    ['Bills D/ST', 'BUF', 'DST'],
    ['Chargers D/ST', 'LAC', 'DST']
  ];

  var NARROW_TIER_BANDS = [3, 3, 4, 5, 6]; // QB/TE/K/DST
  var WIDE_TIER_BANDS = [4, 6, 8, 10, 12, 14]; // RB/WR

  // posIndex is 1-based rank within its own position; past the last band, flat catch-all tier 7 (never a cycle)
  function tierFor(position, posIndex) {
    var bands = (position === 'RB' || position === 'WR') ? WIDE_TIER_BANDS : NARROW_TIER_BANDS;
    var cum = 0;
    for (var i = 0; i < bands.length; i++) {
      cum += bands[i];
      if (posIndex <= cum) {
        return i + 1;
      }
    }
    return 7;
  }

  function hashOf(s) { var h = 0; for (var i = 0; i < s.length; i++) { h += s.charCodeAt(i); } return h; }
  // placeholder ADP until real multi-source data lands; sites are renameable labels downstream
  function fakeAdp(id, site, rank) { return Math.max(1, rank + (hashOf(id + site) % 25) - 12); }

  var positionCounters = {};
  var SEED_PLAYERS = RAW_PLAYERS.map(function (row, index) {
    var name = row[0];
    var team = row[1];
    var position = row[2];
    var id = slug(name, team);
    var rank = index + 1;
    positionCounters[position] = (positionCounters[position] || 0) + 1;
    return {
      id: id,
      rank: rank,
      name: name,
      team: team,
      position: position,
      byeWeek: TEAM_BYE_WEEKS[team],
      tier: tierFor(position, positionCounters[position]),
      adp: { espn: fakeAdp(id, 'espn', rank), yahoo: fakeAdp(id, 'yahoo', rank), sleeper: fakeAdp(id, 'sleeper', rank) }
    };
  });

  DC.data = { TEAM_BYE_WEEKS: TEAM_BYE_WEEKS, SEED_PLAYERS: SEED_PLAYERS, slug: slug };
})();
