// GENERATED FILE - do not edit by hand. Regenerate with scripts\build-board.ps1.
(function () {
  'use strict';
  window.DC = window.DC || {};

  /** @typedef {{id:string, rank:number, name:string, team:string, position:string, byeWeek:number}} Player */

  function slug(name, team) {
    return (name + '-' + team).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  }

  /** @type {Object<string, number>} real 2026 bye weeks via ESPN (scripts\build-board.ps1) */
  var TEAM_BYE_WEEKS = {
    ARI: 14,
    ATL: 5,
    BAL: 13,
    BUF: 5,
    CAR: 5,
    CHI: 7,
    CIN: 6,
    CLE: 11,
    DAL: 14,
    DEN: 10,
    DET: 6,
    GB: 11,
    HOU: 8,
    IND: 13,
    JAX: 7,
    KC: 5,
    LAC: 7,
    LAR: 11,
    LV: 13,
    MIA: 6,
    MIN: 6,
    NE: 11,
    NO: 8,
    NYG: 8,
    NYJ: 13,
    PHI: 10,
    PIT: 9,
    SEA: 11,
    SF: 8,
    TB: 10,
    TEN: 9,
    WAS: 7
  };

  // real user rankings bake: 357 skill (REDRAFT-rankings.csv, one dedup drop) + K/DST
  // interleaved by weighted ADP consensus -- see scripts\build-board.ps1
  var SEED_PLAYERS = [
    { id: "jahmyr-gibbs-det", rank: 1, name: "Jahmyr Gibbs", team: "DET", position: "RB", byeWeek: 6, tier: 1, adp: null },
    { id: "bijan-robinson-atl", rank: 2, name: "Bijan Robinson", team: "ATL", position: "RB", byeWeek: 5, tier: 1, adp: null },
    { id: "ja-marr-chase-cin", rank: 3, name: "Ja'Marr Chase", team: "CIN", position: "WR", byeWeek: 6, tier: 1, adp: null },
    { id: "puka-nacua-lar", rank: 4, name: "Puka Nacua", team: "LAR", position: "WR", byeWeek: 11, tier: 1, adp: null },
    { id: "jaxon-smith-njigba-sea", rank: 5, name: "Jaxon Smith-Njigba", team: "SEA", position: "WR", byeWeek: 11, tier: 1, adp: null },
    { id: "christian-mccaffrey-sf", rank: 6, name: "Christian McCaffrey", team: "SF", position: "RB", byeWeek: 8, tier: 2, adp: null },
    { id: "amon-ra-st-brown-det", rank: 7, name: "Amon-Ra St. Brown", team: "DET", position: "WR", byeWeek: 6, tier: 1, adp: null },
    { id: "jonathan-taylor-ind", rank: 8, name: "Jonathan Taylor", team: "IND", position: "RB", byeWeek: 13, tier: 2, adp: null },
    { id: "ceedee-lamb-dal", rank: 9, name: "CeeDee Lamb", team: "DAL", position: "WR", byeWeek: 14, tier: 1, adp: null },
    { id: "justin-jefferson-min", rank: 10, name: "Justin Jefferson", team: "MIN", position: "WR", byeWeek: 6, tier: 1, adp: null },
    { id: "james-cook-buf", rank: 11, name: "James Cook", team: "BUF", position: "RB", byeWeek: 5, tier: 3, adp: null },
    { id: "ashton-jeanty-lv", rank: 12, name: "Ashton Jeanty", team: "LV", position: "RB", byeWeek: 13, tier: 3, adp: null },
    { id: "chase-brown-cin", rank: 13, name: "Chase Brown", team: "CIN", position: "RB", byeWeek: 6, tier: 3, adp: null },
    { id: "omarion-hampton-lac", rank: 14, name: "Omarion Hampton", team: "LAC", position: "RB", byeWeek: 7, tier: 3, adp: null },
    { id: "devon-achane-mia", rank: 15, name: "Devon Achane", team: "MIA", position: "RB", byeWeek: 6, tier: 3, adp: null },
    { id: "saquon-barkley-phi", rank: 16, name: "Saquon Barkley", team: "PHI", position: "RB", byeWeek: 10, tier: 4, adp: null },
    { id: "kenneth-walker-kc", rank: 17, name: "Kenneth Walker", team: "KC", position: "RB", byeWeek: 5, tier: 4, adp: null },
    { id: "drake-london-atl", rank: 18, name: "Drake London", team: "ATL", position: "WR", byeWeek: 5, tier: 1, adp: null },
    { id: "brock-bowers-lv", rank: 19, name: "Brock Bowers", team: "LV", position: "TE", byeWeek: 13, tier: 1, adp: null },
    { id: "derrick-henry-bal", rank: 20, name: "Derrick Henry", team: "BAL", position: "RB", byeWeek: 13, tier: 4, adp: null },
    { id: "a-j-brown-ne", rank: 21, name: "A.J. Brown", team: "NE", position: "WR", byeWeek: 11, tier: 1, adp: null },
    { id: "malik-nabers-nyg", rank: 22, name: "Malik Nabers", team: "NYG", position: "WR", byeWeek: 8, tier: 1, adp: null },
    { id: "nico-collins-hou", rank: 23, name: "Nico Collins", team: "HOU", position: "WR", byeWeek: 8, tier: 1, adp: null },
    { id: "jeremiyah-love-ari", rank: 24, name: "Jeremiyah Love", team: "ARI", position: "RB", byeWeek: 14, tier: 4, adp: null },
    { id: "rashee-rice-kc", rank: 25, name: "Rashee Rice", team: "KC", position: "WR", byeWeek: 5, tier: 1, adp: null },
    { id: "george-pickens-dal", rank: 26, name: "George Pickens", team: "DAL", position: "WR", byeWeek: 14, tier: 1, adp: null },
    { id: "trey-mcbride-ari", rank: 27, name: "Trey McBride", team: "ARI", position: "TE", byeWeek: 14, tier: 1, adp: null },
    { id: "breece-hall-nyj", rank: 28, name: "Breece Hall", team: "NYJ", position: "RB", byeWeek: 13, tier: 5, adp: null },
    { id: "devonta-smith-phi", rank: 29, name: "DeVonta Smith", team: "PHI", position: "WR", byeWeek: 10, tier: 1, adp: null },
    { id: "chris-olave-no", rank: 30, name: "Chris Olave", team: "NO", position: "WR", byeWeek: 8, tier: 1, adp: null },
    { id: "kyren-williams-lar", rank: 31, name: "Kyren Williams", team: "LAR", position: "RB", byeWeek: 11, tier: 5, adp: null },
    { id: "javonte-williams-dal", rank: 32, name: "Javonte Williams", team: "DAL", position: "RB", byeWeek: 14, tier: 5, adp: null },
    { id: "zay-flowers-bal", rank: 33, name: "Zay Flowers", team: "BAL", position: "WR", byeWeek: 13, tier: 1, adp: null },
    { id: "tee-higgins-cin", rank: 34, name: "Tee Higgins", team: "CIN", position: "WR", byeWeek: 6, tier: 1, adp: null },
    { id: "josh-allen-buf", rank: 35, name: "Josh Allen", team: "BUF", position: "QB", byeWeek: 5, tier: 1, adp: null },
    { id: "josh-jacobs-gb", rank: 36, name: "Josh Jacobs", team: "GB", position: "RB", byeWeek: 11, tier: 5, adp: null },
    { id: "jaylen-waddle-den", rank: 37, name: "Jaylen Waddle", team: "DEN", position: "WR", byeWeek: 10, tier: 1, adp: null },
    { id: "emeka-egbuka-tb", rank: 38, name: "Emeka Egbuka", team: "TB", position: "WR", byeWeek: 10, tier: 1, adp: null },
    { id: "ladd-mcconkey-lac", rank: 39, name: "Ladd McConkey", team: "LAC", position: "WR", byeWeek: 7, tier: 2, adp: null },
    { id: "colston-loveland-chi", rank: 40, name: "Colston Loveland", team: "CHI", position: "TE", byeWeek: 7, tier: 2, adp: null },
    { id: "cam-skattebo-nyg", rank: 41, name: "Cam Skattebo", team: "NYG", position: "RB", byeWeek: 8, tier: 6, adp: null },
    { id: "garrett-wilson-nyj", rank: 42, name: "Garrett Wilson", team: "NYJ", position: "WR", byeWeek: 13, tier: 2, adp: null },
    { id: "tetairoa-mcmillan-car", rank: 43, name: "Tetairoa McMillan", team: "CAR", position: "WR", byeWeek: 5, tier: 2, adp: null },
    { id: "travis-etienne-no", rank: 44, name: "Travis Etienne", team: "NO", position: "RB", byeWeek: 8, tier: 6, adp: null },
    { id: "bucky-irving-tb", rank: 45, name: "Bucky Irving", team: "TB", position: "RB", byeWeek: 10, tier: 6, adp: null },
    { id: "davante-adams-lar", rank: 46, name: "Davante Adams", team: "LAR", position: "WR", byeWeek: 11, tier: 3, adp: null },
    { id: "bhayshul-tuten-jax", rank: 47, name: "Bhayshul Tuten", team: "JAX", position: "RB", byeWeek: 7, tier: 6, adp: null },
    { id: "david-montgomery-hou", rank: 48, name: "David Montgomery", team: "HOU", position: "RB", byeWeek: 8, tier: 6, adp: null },
    { id: "terry-mclaurin-was", rank: 49, name: "Terry McLaurin", team: "WAS", position: "WR", byeWeek: 7, tier: 3, adp: null },
    { id: "d-andre-swift-chi", rank: 50, name: "D'Andre Swift", team: "CHI", position: "RB", byeWeek: 7, tier: 7, adp: null },
    { id: "jameson-williams-det", rank: 51, name: "Jameson Williams", team: "DET", position: "WR", byeWeek: 6, tier: 3, adp: null },
    { id: "quinshon-judkins-cle", rank: 52, name: "Quinshon Judkins", team: "CLE", position: "RB", byeWeek: 11, tier: 7, adp: null },
    { id: "luther-burden-chi", rank: 53, name: "Luther Burden", team: "CHI", position: "WR", byeWeek: 7, tier: 3, adp: null },
    { id: "treveyon-henderson-ne", rank: 54, name: "TreVeyon Henderson", team: "NE", position: "RB", byeWeek: 11, tier: 7, adp: null },
    { id: "mike-evans-sf", rank: 55, name: "Mike Evans", team: "SF", position: "WR", byeWeek: 8, tier: 3, adp: null },
    { id: "lamar-jackson-bal", rank: 56, name: "Lamar Jackson", team: "BAL", position: "QB", byeWeek: 13, tier: 2, adp: null },
    { id: "carnell-tate-ten", rank: 57, name: "Carnell Tate", team: "TEN", position: "WR", byeWeek: 9, tier: 4, adp: null },
    { id: "jadarian-price-sea", rank: 58, name: "Jadarian Price", team: "SEA", position: "RB", byeWeek: 11, tier: 7, adp: null },
    { id: "rome-odunze-chi", rank: 59, name: "Rome Odunze", team: "CHI", position: "WR", byeWeek: 7, tier: 4, adp: null },
    { id: "brian-thomas-jax", rank: 60, name: "Brian Thomas", team: "JAX", position: "WR", byeWeek: 7, tier: 4, adp: null },
    { id: "tyler-warren-ind", rank: 61, name: "Tyler Warren", team: "IND", position: "TE", byeWeek: 13, tier: 3, adp: null },
    { id: "dj-moore-buf", rank: 62, name: "DJ Moore", team: "BUF", position: "WR", byeWeek: 5, tier: 4, adp: null },
    { id: "christian-watson-gb", rank: 63, name: "Christian Watson", team: "GB", position: "WR", byeWeek: 11, tier: 4, adp: null },
    { id: "marvin-harrison-ari", rank: 64, name: "Marvin Harrison", team: "ARI", position: "WR", byeWeek: 14, tier: 4, adp: null },
    { id: "jordyn-tyson-no", rank: 65, name: "Jordyn Tyson", team: "NO", position: "WR", byeWeek: 8, tier: 4, adp: null },
    { id: "drake-maye-ne", rank: 66, name: "Drake Maye", team: "NE", position: "QB", byeWeek: 11, tier: 2, adp: null },
    { id: "jayden-daniels-was", rank: 67, name: "Jayden Daniels", team: "WAS", position: "QB", byeWeek: 7, tier: 3, adp: null },
    { id: "joe-burrow-cin", rank: 68, name: "Joe Burrow", team: "CIN", position: "QB", byeWeek: 6, tier: 3, adp: null },
    { id: "jaylen-warren-pit", rank: 69, name: "Jaylen Warren", team: "PIT", position: "RB", byeWeek: 9, tier: 7, adp: null },
    { id: "parker-washington-jax", rank: 70, name: "Parker Washington", team: "JAX", position: "WR", byeWeek: 7, tier: 4, adp: null },
    { id: "caleb-williams-chi", rank: 71, name: "Caleb Williams", team: "CHI", position: "QB", byeWeek: 7, tier: 3, adp: null },
    { id: "jalen-hurts-phi", rank: 72, name: "Jalen Hurts", team: "PHI", position: "QB", byeWeek: 10, tier: 3, adp: null },
    { id: "tucker-kraft-gb", rank: 73, name: "Tucker Kraft", team: "GB", position: "TE", byeWeek: 11, tier: 4, adp: null },
    { id: "makai-lemon-phi", rank: 74, name: "Makai Lemon", team: "PHI", position: "WR", byeWeek: 10, tier: 5, adp: null },
    { id: "tony-pollard-ten", rank: 75, name: "Tony Pollard", team: "TEN", position: "RB", byeWeek: 9, tier: 8, adp: null },
    { id: "jonathon-brooks-car", rank: 76, name: "Jonathon Brooks", team: "CAR", position: "RB", byeWeek: 5, tier: 8, adp: null },
    { id: "rhamondre-stevenson-ne", rank: 77, name: "Rhamondre Stevenson", team: "NE", position: "RB", byeWeek: 11, tier: 8, adp: null },
    { id: "quentin-johnston-lac", rank: 78, name: "Quentin Johnston", team: "LAC", position: "WR", byeWeek: 7, tier: 5, adp: null },
    { id: "sam-laporta-det", rank: 79, name: "Sam LaPorta", team: "DET", position: "TE", byeWeek: 6, tier: 4, adp: null },
    { id: "trevor-lawrence-jax", rank: 80, name: "Trevor Lawrence", team: "JAX", position: "QB", byeWeek: 7, tier: 4, adp: null },
    { id: "jordan-addison-min", rank: 81, name: "Jordan Addison", team: "MIN", position: "WR", byeWeek: 6, tier: 5, adp: null },
    { id: "michael-pittman-pit", rank: 82, name: "Michael Pittman", team: "PIT", position: "WR", byeWeek: 9, tier: 5, adp: null },
    { id: "alec-pierce-ind", rank: 83, name: "Alec Pierce", team: "IND", position: "WR", byeWeek: 13, tier: 5, adp: null },
    { id: "dk-metcalf-pit", rank: 84, name: "DK Metcalf", team: "PIT", position: "WR", byeWeek: 9, tier: 5, adp: null },
    { id: "chris-godwin-tb", rank: 85, name: "Chris Godwin", team: "TB", position: "WR", byeWeek: 10, tier: 5, adp: null },
    { id: "rj-harvey-den", rank: 86, name: "RJ Harvey", team: "DEN", position: "RB", byeWeek: 10, tier: 8, adp: null },
    { id: "justin-herbert-lac", rank: 87, name: "Justin Herbert", team: "LAC", position: "QB", byeWeek: 7, tier: 4, adp: null },
    { id: "j-k-dobbins-den", rank: 88, name: "J.K. Dobbins", team: "DEN", position: "RB", byeWeek: 10, tier: 8, adp: null },
    { id: "courtland-sutton-den", rank: 89, name: "Courtland Sutton", team: "DEN", position: "WR", byeWeek: 10, tier: 5, adp: null },
    { id: "rachaad-white-was", rank: 90, name: "Rachaad White", team: "WAS", position: "RB", byeWeek: 7, tier: 9, adp: null },
    { id: "stefon-diggs-was", rank: 91, name: "Stefon Diggs", team: "WAS", position: "WR", byeWeek: 7, tier: 5, adp: null },
    { id: "rico-dowdle-pit", rank: 92, name: "Rico Dowdle", team: "PIT", position: "RB", byeWeek: 9, tier: 9, adp: null },
    { id: "dak-prescott-dal", rank: 93, name: "Dak Prescott", team: "DAL", position: "QB", byeWeek: 14, tier: 4, adp: null },
    { id: "michael-wilson-ari", rank: 94, name: "Michael Wilson", team: "ARI", position: "WR", byeWeek: 14, tier: 5, adp: null },
    { id: "harold-fannin-cle", rank: 95, name: "Harold Fannin", team: "CLE", position: "TE", byeWeek: 11, tier: 4, adp: null },
    { id: "chuba-hubbard-car", rank: 96, name: "Chuba Hubbard", team: "CAR", position: "RB", byeWeek: 5, tier: 9, adp: null },
    { id: "josh-downs-ind", rank: 97, name: "Josh Downs", team: "IND", position: "WR", byeWeek: 13, tier: 5, adp: null },
    { id: "kyle-pitts-atl", rank: 98, name: "Kyle Pitts", team: "ATL", position: "TE", byeWeek: 5, tier: 4, adp: null },
    { id: "blake-corum-lar", rank: 99, name: "Blake Corum", team: "LAR", position: "RB", byeWeek: 11, tier: 9, adp: null },
    { id: "jordan-mason-min", rank: 100, name: "Jordan Mason", team: "MIN", position: "RB", byeWeek: 6, tier: 9, adp: null },
    { id: "kyle-monangai-chi", rank: 101, name: "Kyle Monangai", team: "CHI", position: "RB", byeWeek: 7, tier: 9, adp: null },
    { id: "jaxson-dart-nyg", rank: 102, name: "Jaxson Dart", team: "NYG", position: "QB", byeWeek: 8, tier: 4, adp: null },
    { id: "brock-purdy-sf", rank: 103, name: "Brock Purdy", team: "SF", position: "QB", byeWeek: 8, tier: 4, adp: null },
    { id: "wan-dale-robinson-ten", rank: 104, name: "Wan'Dale Robinson", team: "TEN", position: "WR", byeWeek: 9, tier: 5, adp: null },
    { id: "rams-d-st-lar", rank: 105, name: "Rams D/ST", team: "LAR", position: "DST", byeWeek: 11, tier: null, adp: null },
    { id: "kc-concepcion-cle", rank: 106, name: "KC Concepcion", team: "CLE", position: "WR", byeWeek: 11, tier: 5, adp: null },
    { id: "bo-nix-den", rank: 107, name: "Bo Nix", team: "DEN", position: "QB", byeWeek: 10, tier: 5, adp: null },
    { id: "jayden-reed-gb", rank: 108, name: "Jayden Reed", team: "GB", position: "WR", byeWeek: 11, tier: 5, adp: null },
    { id: "patrick-mahomes-kc", rank: 109, name: "Patrick Mahomes", team: "KC", position: "QB", byeWeek: 5, tier: 5, adp: null },
    { id: "xavier-worthy-kc", rank: 110, name: "Xavier Worthy", team: "KC", position: "WR", byeWeek: 5, tier: 5, adp: null },
    { id: "jacory-croskey-merritt-was", rank: 111, name: "Jacory Croskey-Merritt", team: "WAS", position: "RB", byeWeek: 7, tier: 9, adp: null },
    { id: "kenneth-gainwell-tb", rank: 112, name: "Kenneth Gainwell", team: "TB", position: "RB", byeWeek: 10, tier: 9, adp: null },
    { id: "george-kittle-sf", rank: 113, name: "George Kittle", team: "SF", position: "TE", byeWeek: 8, tier: 5, adp: null },
    { id: "matthew-stafford-lar", rank: 114, name: "Matthew Stafford", team: "LAR", position: "QB", byeWeek: 11, tier: 5, adp: null },
    { id: "jared-goff-det", rank: 115, name: "Jared Goff", team: "DET", position: "QB", byeWeek: 6, tier: 5, adp: null },
    { id: "texans-d-st-hou", rank: 116, name: "Texans D/ST", team: "HOU", position: "DST", byeWeek: 8, tier: null, adp: null },
    { id: "deebo-samuel-sf", rank: 117, name: "Deebo Samuel", team: "SF", position: "WR", byeWeek: 8, tier: 5, adp: null },
    { id: "seahawks-d-st-sea", rank: 118, name: "Seahawks D/ST", team: "SEA", position: "DST", byeWeek: 11, tier: null, adp: null },
    { id: "kyler-murray-min", rank: 119, name: "Kyler Murray", team: "MIN", position: "QB", byeWeek: 6, tier: 5, adp: null },
    { id: "travis-kelce-kc", rank: 120, name: "Travis Kelce", team: "KC", position: "TE", byeWeek: 5, tier: 5, adp: null },
    { id: "jakobi-meyers-jax", rank: 121, name: "Jakobi Meyers", team: "JAX", position: "WR", byeWeek: 7, tier: 5, adp: null },
    { id: "matthew-golden-gb", rank: 122, name: "Matthew Golden", team: "GB", position: "WR", byeWeek: 11, tier: 5, adp: null },
    { id: "aaron-jones-min", rank: 123, name: "Aaron Jones", team: "MIN", position: "RB", byeWeek: 6, tier: 10, adp: null },
    { id: "travis-hunter-jax", rank: 124, name: "Travis Hunter", team: "JAX", position: "WR", byeWeek: 7, tier: 5, adp: null },
    { id: "romeo-doubs-ne", rank: 125, name: "Romeo Doubs", team: "NE", position: "WR", byeWeek: 11, tier: 5, adp: null },
    { id: "jalen-coker-car", rank: 126, name: "Jalen Coker", team: "CAR", position: "WR", byeWeek: 5, tier: 5, adp: null },
    { id: "jayden-higgins-hou", rank: 127, name: "Jayden Higgins", team: "HOU", position: "WR", byeWeek: 8, tier: 5, adp: null },
    { id: "jake-ferguson-dal", rank: 128, name: "Jake Ferguson", team: "DAL", position: "TE", byeWeek: 14, tier: 5, adp: null },
    { id: "baker-mayfield-tb", rank: 129, name: "Baker Mayfield", team: "TB", position: "QB", byeWeek: 10, tier: 5, adp: null },
    { id: "chris-rodriguez-jax", rank: 130, name: "Chris Rodriguez", team: "JAX", position: "RB", byeWeek: 7, tier: 10, adp: null },
    { id: "isaiah-likely-nyg", rank: 131, name: "Isaiah Likely", team: "NYG", position: "TE", byeWeek: 8, tier: 5, adp: null },
    { id: "mark-andrews-bal", rank: 132, name: "Mark Andrews", team: "BAL", position: "TE", byeWeek: 13, tier: 6, adp: null },
    { id: "tyler-shough-no", rank: 133, name: "Tyler Shough", team: "NO", position: "QB", byeWeek: 8, tier: 6, adp: null },
    { id: "broncos-d-st-den", rank: 134, name: "Broncos D/ST", team: "DEN", position: "DST", byeWeek: 10, tier: null, adp: null },
    { id: "brandon-aubrey-dal", rank: 135, name: "Brandon Aubrey", team: "DAL", position: "K", byeWeek: 14, tier: null, adp: null },
    { id: "tyrone-tracy-nyg", rank: 136, name: "Tyrone Tracy", team: "NYG", position: "RB", byeWeek: 8, tier: 10, adp: null },
    { id: "dalton-kincaid-buf", rank: 137, name: "Dalton Kincaid", team: "BUF", position: "TE", byeWeek: 5, tier: 6, adp: null },
    { id: "khalil-shakir-buf", rank: 138, name: "Khalil Shakir", team: "BUF", position: "WR", byeWeek: 5, tier: 5, adp: null },
    { id: "rashid-shaheed-sea", rank: 139, name: "Rashid Shaheed", team: "SEA", position: "WR", byeWeek: 11, tier: 5, adp: null },
    { id: "woody-marks-hou", rank: 140, name: "Woody Marks", team: "HOU", position: "RB", byeWeek: 8, tier: 10, adp: null },
    { id: "jordan-love-gb", rank: 141, name: "Jordan Love", team: "GB", position: "QB", byeWeek: 11, tier: 6, adp: null },
    { id: "eagles-d-st-phi", rank: 142, name: "Eagles D/ST", team: "PHI", position: "DST", byeWeek: 10, tier: null, adp: null },
    { id: "cameron-dicker-lac", rank: 143, name: "Cameron Dicker", team: "LAC", position: "K", byeWeek: 7, tier: null, adp: null },
    { id: "jason-myers-sea", rank: 144, name: "Jason Myers", team: "SEA", position: "K", byeWeek: 11, tier: null, adp: null },
    { id: "ravens-d-st-bal", rank: 145, name: "Ravens D/ST", team: "BAL", position: "DST", byeWeek: 13, tier: null, adp: null },
    { id: "ka-imi-fairbairn-hou", rank: 146, name: "Ka'imi Fairbairn", team: "HOU", position: "K", byeWeek: 8, tier: null, adp: null },
    { id: "patriots-d-st-ne", rank: 147, name: "Patriots D/ST", team: "NE", position: "DST", byeWeek: 11, tier: null, adp: null },
    { id: "cam-little-jax", rank: 148, name: "Cam Little", team: "JAX", position: "K", byeWeek: 7, tier: null, adp: null },
    { id: "jonah-coleman-den", rank: 149, name: "Jonah Coleman", team: "DEN", position: "RB", byeWeek: 10, tier: 10, adp: null },
    { id: "denzel-boston-cle", rank: 150, name: "Denzel Boston", team: "CLE", position: "WR", byeWeek: 11, tier: 5, adp: null },
    { id: "malik-willis-mia", rank: 151, name: "Malik Willis", team: "MIA", position: "QB", byeWeek: 6, tier: 6, adp: null },
    { id: "keaton-mitchell-lac", rank: 152, name: "Keaton Mitchell", team: "LAC", position: "RB", byeWeek: 7, tier: 10, adp: null },
    { id: "omar-cooper-jr-nyj", rank: 153, name: "Omar Cooper Jr.", team: "NYJ", position: "WR", byeWeek: 13, tier: 5, adp: null },
    { id: "dallas-goedert-phi", rank: 154, name: "Dallas Goedert", team: "PHI", position: "TE", byeWeek: 10, tier: 6, adp: null },
    { id: "de-zhaun-stribling-sf", rank: 155, name: "De'Zhaun Stribling", team: "SF", position: "WR", byeWeek: 8, tier: 5, adp: null },
    { id: "lions-d-st-det", rank: 156, name: "Lions D/ST", team: "DET", position: "DST", byeWeek: 6, tier: null, adp: null },
    { id: "harrison-mevis-lar", rank: 157, name: "Harrison Mevis", team: "LAR", position: "K", byeWeek: 11, tier: null, adp: null },
    { id: "jalen-mcmillan-tb", rank: 158, name: "Jalen McMillan", team: "TB", position: "WR", byeWeek: 10, tier: 6, adp: null },
    { id: "isiah-pacheco-det", rank: 159, name: "Isiah Pacheco", team: "DET", position: "RB", byeWeek: 6, tier: 10, adp: null },
    { id: "tank-bigsby-phi", rank: 160, name: "Tank Bigsby", team: "PHI", position: "RB", byeWeek: 10, tier: 10, adp: null },
    { id: "chig-okonkwo-was", rank: 161, name: "Chig Okonkwo", team: "WAS", position: "TE", byeWeek: 7, tier: 6, adp: null },
    { id: "steelers-d-st-pit", rank: 162, name: "Steelers D/ST", team: "PIT", position: "DST", byeWeek: 9, tier: null, adp: null },
    { id: "tre-tucker-lv", rank: 163, name: "Tre Tucker", team: "LV", position: "WR", byeWeek: 13, tier: 6, adp: null },
    { id: "oronde-gadsden-lac", rank: 164, name: "Oronde Gadsden", team: "LAC", position: "TE", byeWeek: 7, tier: 6, adp: null },
    { id: "brenton-strange-jax", rank: 165, name: "Brenton Strange", team: "JAX", position: "TE", byeWeek: 7, tier: 7, adp: null },
    { id: "tyler-allgeier-ari", rank: 166, name: "Tyler Allgeier", team: "ARI", position: "RB", byeWeek: 14, tier: 10, adp: null },
    { id: "c-j-stroud-hou", rank: 167, name: "C.J. Stroud", team: "HOU", position: "QB", byeWeek: 8, tier: 6, adp: null },
    { id: "sam-darnold-sea", rank: 168, name: "Sam Darnold", team: "SEA", position: "QB", byeWeek: 11, tier: 6, adp: null },
    { id: "cam-ward-ten", rank: 169, name: "Cam Ward", team: "TEN", position: "QB", byeWeek: 9, tier: 7, adp: null },
    { id: "hunter-henry-ne", rank: 170, name: "Hunter Henry", team: "NE", position: "TE", byeWeek: 11, tier: 7, adp: null },
    { id: "daniel-jones-ind", rank: 171, name: "Daniel Jones", team: "IND", position: "QB", byeWeek: 13, tier: 7, adp: null },
    { id: "alvin-kamara-no", rank: 172, name: "Alvin Kamara", team: "NO", position: "RB", byeWeek: 8, tier: 10, adp: null },
    { id: "kenyon-sadiq-nyj", rank: 173, name: "Kenyon Sadiq", team: "NYJ", position: "TE", byeWeek: 13, tier: 7, adp: null },
    { id: "dylan-sampson-cle", rank: 174, name: "Dylan Sampson", team: "CLE", position: "RB", byeWeek: 11, tier: 10, adp: null },
    { id: "zach-charbonnet-sea", rank: 175, name: "Zach Charbonnet", team: "SEA", position: "RB", byeWeek: 11, tier: 10, adp: null },
    { id: "eddy-pineiro-sf", rank: 176, name: "Eddy Pineiro", team: "SF", position: "K", byeWeek: 8, tier: null, adp: null },
    { id: "will-reichard-min", rank: 177, name: "Will Reichard", team: "MIN", position: "K", byeWeek: 6, tier: null, adp: null },
    { id: "chargers-d-st-lac", rank: 178, name: "Chargers D/ST", team: "LAC", position: "DST", byeWeek: 7, tier: null, adp: null },
    { id: "jake-bates-det", rank: 179, name: "Jake Bates", team: "DET", position: "K", byeWeek: 6, tier: null, adp: null },
    { id: "harrison-butker-kc", rank: 180, name: "Harrison Butker", team: "KC", position: "K", byeWeek: 5, tier: null, adp: null },
    { id: "bryce-young-car", rank: 181, name: "Bryce Young", team: "CAR", position: "QB", byeWeek: 5, tier: 7, adp: null },
    { id: "tyjae-spears-ten", rank: 182, name: "Tyjae Spears", team: "TEN", position: "RB", byeWeek: 9, tier: 11, adp: null },
    { id: "t-j-hockenson-min", rank: 183, name: "T.J. Hockenson", team: "MIN", position: "TE", byeWeek: 6, tier: 7, adp: null },
    { id: "jalen-nailor-lv", rank: 184, name: "Jalen Nailor", team: "LV", position: "WR", byeWeek: 13, tier: 6, adp: null },
    { id: "brian-robinson-atl", rank: 185, name: "Brian Robinson", team: "ATL", position: "RB", byeWeek: 5, tier: 11, adp: null },
    { id: "juwan-johnson-no", rank: 186, name: "Juwan Johnson", team: "NO", position: "TE", byeWeek: 8, tier: 7, adp: null },
    { id: "aj-barner-sea", rank: 187, name: "AJ Barner", team: "SEA", position: "TE", byeWeek: 11, tier: 7, adp: null },
    { id: "dalton-schultz-hou", rank: 188, name: "Dalton Schultz", team: "HOU", position: "TE", byeWeek: 8, tier: 7, adp: null },
    { id: "cairo-santos-chi", rank: 189, name: "Cairo Santos", team: "CHI", position: "K", byeWeek: 7, tier: null, adp: null },
    { id: "chris-boswell-pit", rank: 190, name: "Chris Boswell", team: "PIT", position: "K", byeWeek: 9, tier: null, adp: null },
    { id: "jaguars-d-st-jax", rank: 191, name: "Jaguars D/ST", team: "JAX", position: "DST", byeWeek: 7, tier: null, adp: null },
    { id: "chiefs-d-st-kc", rank: 192, name: "Chiefs D/ST", team: "KC", position: "DST", byeWeek: 5, tier: null, adp: null },
    { id: "tyler-loop-bal", rank: 193, name: "Tyler Loop", team: "BAL", position: "K", byeWeek: 13, tier: null, adp: null },
    { id: "vikings-d-st-min", rank: 194, name: "Vikings D/ST", team: "MIN", position: "DST", byeWeek: 6, tier: null, adp: null },
    { id: "evan-mcpherson-cin", rank: 195, name: "Evan McPherson", team: "CIN", position: "K", byeWeek: 6, tier: null, adp: null },
    { id: "packers-d-st-gb", rank: 196, name: "Packers D/ST", team: "GB", position: "DST", byeWeek: 11, tier: null, adp: null },
    { id: "andy-borregales-ne", rank: 197, name: "Andy Borregales", team: "NE", position: "K", byeWeek: 11, tier: null, adp: null },
    { id: "sean-tucker-tb", rank: 198, name: "Sean Tucker", team: "TB", position: "RB", byeWeek: 10, tier: 11, adp: null },
    { id: "tre-harris-lac", rank: 199, name: "Tre Harris", team: "LAC", position: "WR", byeWeek: 7, tier: 6, adp: null },
    { id: "antonio-williams-was", rank: 200, name: "Antonio Williams", team: "WAS", position: "WR", byeWeek: 7, tier: 6, adp: null },
    { id: "kaytron-allen-was", rank: 201, name: "Kaytron Allen", team: "WAS", position: "RB", byeWeek: 7, tier: 11, adp: null },
    { id: "marshawn-lloyd-gb", rank: 202, name: "MarShawn Lloyd", team: "GB", position: "RB", byeWeek: 11, tier: 11, adp: null },
    { id: "darnell-mooney-nyg", rank: 203, name: "Darnell Mooney", team: "NYG", position: "WR", byeWeek: 8, tier: 6, adp: null },
    { id: "ryan-flournoy-dal", rank: 204, name: "Ryan Flournoy", team: "DAL", position: "WR", byeWeek: 14, tier: 6, adp: null },
    { id: "calvin-ridley-ten", rank: 205, name: "Calvin Ridley", team: "TEN", position: "WR", byeWeek: 9, tier: 7, adp: null },
    { id: "nicholas-singleton-ten", rank: 206, name: "Nicholas Singleton", team: "TEN", position: "RB", byeWeek: 9, tier: 11, adp: null },
    { id: "emmett-johnson-kc", rank: 207, name: "Emmett Johnson", team: "KC", position: "RB", byeWeek: 5, tier: 11, adp: null },
    { id: "malik-washington-mia", rank: 208, name: "Malik Washington", team: "MIA", position: "WR", byeWeek: 6, tier: 7, adp: null },
    { id: "tank-dell-hou", rank: 209, name: "Tank Dell", team: "HOU", position: "WR", byeWeek: 8, tier: 7, adp: null },
    { id: "jerry-jeudy-cle", rank: 210, name: "Jerry Jeudy", team: "CLE", position: "WR", byeWeek: 11, tier: 7, adp: null },
    { id: "zachariah-branch-atl", rank: 211, name: "Zachariah Branch", team: "ATL", position: "WR", byeWeek: 5, tier: 7, adp: null },
    { id: "mike-washington-jr-lv", rank: 212, name: "Mike Washington Jr.", team: "LV", position: "RB", byeWeek: 13, tier: 11, adp: null },
    { id: "jauan-jennings-min", rank: 213, name: "Jauan Jennings", team: "MIN", position: "WR", byeWeek: 6, tier: 7, adp: null },
    { id: "isaac-teslaa-det", rank: 214, name: "Isaac TeSlaa", team: "DET", position: "WR", byeWeek: 6, tier: 7, adp: null },
    { id: "ray-davis-buf", rank: 215, name: "Ray Davis", team: "BUF", position: "RB", byeWeek: 5, tier: 11, adp: null },
    { id: "demond-claiborne-min", rank: 216, name: "Demond Claiborne", team: "MIN", position: "RB", byeWeek: 6, tier: 11, adp: null },
    { id: "gunnar-helm-ten", rank: 217, name: "Gunnar Helm", team: "TEN", position: "TE", byeWeek: 9, tier: 8, adp: null },
    { id: "chase-mclaughlin-tb", rank: 218, name: "Chase McLaughlin", team: "TB", position: "K", byeWeek: 10, tier: null, adp: null },
    { id: "colts-d-st-ind", rank: 219, name: "Colts D/ST", team: "IND", position: "DST", byeWeek: 13, tier: null, adp: null },
    { id: "buccaneers-d-st-tb", rank: 220, name: "Buccaneers D/ST", team: "TB", position: "DST", byeWeek: 10, tier: null, adp: null },
    { id: "chris-brooks-gb", rank: 221, name: "Chris Brooks", team: "GB", position: "RB", byeWeek: 11, tier: 11, adp: null },
    { id: "49ers-d-st-sf", rank: 222, name: "49ers D/ST", team: "SF", position: "DST", byeWeek: 8, tier: null, adp: null },
    { id: "bears-d-st-chi", rank: 223, name: "Bears D/ST", team: "CHI", position: "DST", byeWeek: 7, tier: null, adp: null },
    { id: "cowboys-d-st-dal", rank: 224, name: "Cowboys D/ST", team: "DAL", position: "DST", byeWeek: 14, tier: null, adp: null },
    { id: "browns-d-st-cle", rank: 225, name: "Browns D/ST", team: "CLE", position: "DST", byeWeek: 11, tier: null, adp: null },
    { id: "devin-singletary-nyg", rank: 226, name: "Devin Singletary", team: "NYG", position: "RB", byeWeek: 8, tier: 11, adp: null },
    { id: "brashard-smith-kc", rank: 227, name: "Brashard Smith", team: "KC", position: "RB", byeWeek: 5, tier: 11, adp: null },
    { id: "germie-bernard-pit", rank: 228, name: "Germie Bernard", team: "PIT", position: "WR", byeWeek: 9, tier: 7, adp: null },
    { id: "terrance-ferguson-lar", rank: 229, name: "Terrance Ferguson", team: "LAR", position: "TE", byeWeek: 11, tier: 8, adp: null },
    { id: "elijah-sarratt-bal", rank: 230, name: "Elijah Sarratt", team: "BAL", position: "WR", byeWeek: 13, tier: 7, adp: null },
    { id: "david-njoku-lac", rank: 231, name: "David Njoku", team: "LAC", position: "TE", byeWeek: 7, tier: 8, adp: null },
    { id: "aaron-rodgers-pit", rank: 232, name: "Aaron Rodgers", team: "PIT", position: "QB", byeWeek: 9, tier: 7, adp: null },
    { id: "kayshon-boutte-ne", rank: 233, name: "Kayshon Boutte", team: "NE", position: "WR", byeWeek: 11, tier: 8, adp: null },
    { id: "ja-kobi-lane-bal", rank: 234, name: "Ja'Kobi Lane", team: "BAL", position: "WR", byeWeek: 13, tier: 8, adp: null },
    { id: "jacoby-brissett-ari", rank: 235, name: "Jacoby Brissett", team: "ARI", position: "QB", byeWeek: 14, tier: 7, adp: null },
    { id: "braelon-allen-nyj", rank: 236, name: "Braelon Allen", team: "NYJ", position: "RB", byeWeek: 13, tier: 11, adp: null },
    { id: "jaydon-blue-dal", rank: 237, name: "Jaydon Blue", team: "DAL", position: "RB", byeWeek: 14, tier: 11, adp: null },
    { id: "chris-bell-mia", rank: 238, name: "Chris Bell", team: "MIA", position: "WR", byeWeek: 6, tier: 8, adp: null },
    { id: "pat-freiermuth-pit", rank: 239, name: "Pat Freiermuth", team: "PIT", position: "TE", byeWeek: 9, tier: 8, adp: null },
    { id: "ollie-gordon-ii-mia", rank: 240, name: "Ollie Gordon II", team: "MIA", position: "RB", byeWeek: 6, tier: 11, adp: null },
    { id: "troy-franklin-den", rank: 241, name: "Troy Franklin", team: "DEN", position: "WR", byeWeek: 10, tier: 8, adp: null },
    { id: "kimani-vidal-lac", rank: 242, name: "Kimani Vidal", team: "LAC", position: "RB", byeWeek: 7, tier: 11, adp: null },
    { id: "greg-dulcich-mia", rank: 243, name: "Greg Dulcich", team: "MIA", position: "TE", byeWeek: 6, tier: 8, adp: null },
    { id: "cade-otton-tb", rank: 244, name: "Cade Otton", team: "TB", position: "TE", byeWeek: 10, tier: 8, adp: null },
    { id: "adonai-mitchell-nyj", rank: 245, name: "Adonai Mitchell", team: "NYJ", position: "WR", byeWeek: 13, tier: 8, adp: null },
    { id: "bengals-d-st-cin", rank: 246, name: "Bengals D/ST", team: "CIN", position: "DST", byeWeek: 6, tier: null, adp: null },
    { id: "jake-elliott-phi", rank: 247, name: "Jake Elliott", team: "PHI", position: "K", byeWeek: 10, tier: null, adp: null },
    { id: "bills-d-st-buf", rank: 248, name: "Bills D/ST", team: "BUF", position: "DST", byeWeek: 5, tier: null, adp: null },
    { id: "giants-d-st-nyg", rank: 249, name: "Giants D/ST", team: "NYG", position: "DST", byeWeek: 8, tier: null, adp: null },
    { id: "falcons-d-st-atl", rank: 250, name: "Falcons D/ST", team: "ATL", position: "DST", byeWeek: 5, tier: null, adp: null },
    { id: "saints-d-st-no", rank: 251, name: "Saints D/ST", team: "NO", position: "DST", byeWeek: 8, tier: null, adp: null },
    { id: "panthers-d-st-car", rank: 252, name: "Panthers D/ST", team: "CAR", position: "DST", byeWeek: 5, tier: null, adp: null },
    { id: "nick-folk-atl", rank: 253, name: "Nick Folk", team: "ATL", position: "K", byeWeek: 5, tier: null, adp: null },
    { id: "wil-lutz-den", rank: 254, name: "Wil Lutz", team: "DEN", position: "K", byeWeek: 10, tier: null, adp: null },
    { id: "jets-d-st-nyj", rank: 255, name: "Jets D/ST", team: "NYJ", position: "DST", byeWeek: 13, tier: null, adp: null },
    { id: "matt-gay-lv", rank: 256, name: "Matt Gay", team: "LV", position: "K", byeWeek: 13, tier: null, adp: null },
    { id: "charlie-smyth-no", rank: 257, name: "Charlie Smyth", team: "NO", position: "K", byeWeek: 8, tier: null, adp: null },
    { id: "titans-d-st-ten", rank: 258, name: "Titans D/ST", team: "TEN", position: "DST", byeWeek: 9, tier: null, adp: null },
    { id: "cardinals-d-st-ari", rank: 259, name: "Cardinals D/ST", team: "ARI", position: "DST", byeWeek: 14, tier: null, adp: null },
    { id: "raiders-d-st-lv", rank: 260, name: "Raiders D/ST", team: "LV", position: "DST", byeWeek: 13, tier: null, adp: null },
    { id: "najee-harris-fa", rank: 261, name: "Najee Harris", team: "FA", position: "RB", byeWeek: 0, tier: 11, adp: null },
    { id: "eli-stowers-phi", rank: 262, name: "Eli Stowers", team: "PHI", position: "TE", byeWeek: 10, tier: 8, adp: null },
    { id: "ted-hurst-tb", rank: 263, name: "Ted Hurst", team: "TB", position: "WR", byeWeek: 10, tier: 8, adp: null },
    { id: "elic-ayomanor-ten", rank: 264, name: "Elic Ayomanor", team: "TEN", position: "WR", byeWeek: 9, tier: 8, adp: null },
    { id: "geno-smith-nyj", rank: 265, name: "Geno Smith", team: "NYJ", position: "QB", byeWeek: 13, tier: 7, adp: null },
    { id: "george-holani-sea", rank: 266, name: "George Holani", team: "SEA", position: "RB", byeWeek: 11, tier: 11, adp: null },
    { id: "jordan-james-sf", rank: 267, name: "Jordan James", team: "SF", position: "RB", byeWeek: 8, tier: 11, adp: null },
    { id: "dontayvion-wicks-phi", rank: 268, name: "Dontayvion Wicks", team: "PHI", position: "WR", byeWeek: 10, tier: 8, adp: null },
    { id: "fernando-mendoza-lv", rank: 269, name: "Fernando Mendoza", team: "LV", position: "QB", byeWeek: 13, tier: 7, adp: null },
    { id: "adam-randall-bal", rank: 270, name: "Adam Randall", team: "BAL", position: "RB", byeWeek: 13, tier: 11, adp: null },
    { id: "calvin-austin-nyg", rank: 271, name: "Calvin Austin", team: "NYG", position: "WR", byeWeek: 8, tier: 8, adp: null },
    { id: "darius-slayton-nyg", rank: 272, name: "Darius Slayton", team: "NYG", position: "WR", byeWeek: 8, tier: 9, adp: null },
    { id: "caleb-douglas-mia", rank: 273, name: "Caleb Douglas", team: "MIA", position: "WR", byeWeek: 6, tier: 9, adp: null },
    { id: "malachi-fields-nyg", rank: 274, name: "Malachi Fields", team: "NYG", position: "WR", byeWeek: 8, tier: 9, adp: null },
    { id: "james-conner-ari", rank: 275, name: "James Conner", team: "ARI", position: "RB", byeWeek: 14, tier: 12, adp: null },
    { id: "luke-mccaffrey-was", rank: 276, name: "Luke McCaffrey", team: "WAS", position: "WR", byeWeek: 7, tier: 9, adp: null },
    { id: "cyrus-allen-kc", rank: 277, name: "Cyrus Allen", team: "KC", position: "WR", byeWeek: 5, tier: 9, adp: null },
    { id: "samaje-perine-cin", rank: 278, name: "Samaje Perine", team: "CIN", position: "RB", byeWeek: 6, tier: 12, adp: null },
    { id: "keon-coleman-buf", rank: 279, name: "Keon Coleman", team: "BUF", position: "WR", byeWeek: 5, tier: 9, adp: null },
    { id: "chimere-dike-ten", rank: 280, name: "Chimere Dike", team: "TEN", position: "WR", byeWeek: 9, tier: 9, adp: null },
    { id: "ty-johnson-buf", rank: 281, name: "Ty Johnson", team: "BUF", position: "RB", byeWeek: 5, tier: 12, adp: null },
    { id: "jack-bech-lv", rank: 282, name: "Jack Bech", team: "LV", position: "WR", byeWeek: 13, tier: 9, adp: null },
    { id: "tory-horton-sea", rank: 283, name: "Tory Horton", team: "SEA", position: "WR", byeWeek: 11, tier: 9, adp: null },
    { id: "justice-hill-bal", rank: 284, name: "Justice Hill", team: "BAL", position: "RB", byeWeek: 13, tier: 12, adp: null },
    { id: "christian-kirk-sf", rank: 285, name: "Christian Kirk", team: "SF", position: "WR", byeWeek: 8, tier: 9, adp: null },
    { id: "tez-johnson-tb", rank: 286, name: "Tez Johnson", team: "TB", position: "WR", byeWeek: 10, tier: 9, adp: null },
    { id: "bryce-lance-no", rank: 287, name: "Bryce Lance", team: "NO", position: "WR", byeWeek: 8, tier: 9, adp: null },
    { id: "jaylin-noel-hou", rank: 288, name: "Jaylin Noel", team: "HOU", position: "WR", byeWeek: 8, tier: 9, adp: null },
    { id: "dj-giddens-ind", rank: 289, name: "DJ Giddens", team: "IND", position: "RB", byeWeek: 13, tier: 12, adp: null },
    { id: "tua-tagovailoa-atl", rank: 290, name: "Tua Tagovailoa", team: "ATL", position: "QB", byeWeek: 5, tier: 7, adp: null },
    { id: "isaiah-davis-nyj", rank: 291, name: "Isaiah Davis", team: "NYJ", position: "RB", byeWeek: 13, tier: 12, adp: null },
    { id: "kendre-miller-no", rank: 292, name: "Kendre Miller", team: "NO", position: "RB", byeWeek: 8, tier: 12, adp: null },
    { id: "tyquan-thornton-kc", rank: 293, name: "Tyquan Thornton", team: "KC", position: "WR", byeWeek: 5, tier: 9, adp: null },
    { id: "pat-bryant-den", rank: 294, name: "Pat Bryant", team: "DEN", position: "WR", byeWeek: 10, tier: 9, adp: null },
    { id: "skyler-bell-buf", rank: 295, name: "Skyler Bell", team: "BUF", position: "WR", byeWeek: 5, tier: 9, adp: null },
    { id: "rashod-bateman-bal", rank: 296, name: "Rashod Bateman", team: "BAL", position: "WR", byeWeek: 13, tier: 9, adp: null },
    { id: "cedric-tillman-cle", rank: 297, name: "Cedric Tillman", team: "CLE", position: "WR", byeWeek: 11, tier: 10, adp: null },
    { id: "mike-gesicki-cin", rank: 298, name: "Mike Gesicki", team: "CIN", position: "TE", byeWeek: 6, tier: 9, adp: null },
    { id: "tyler-bass-buf", rank: 299, name: "Tyler Bass", team: "BUF", position: "K", byeWeek: 5, tier: null, adp: null },
    { id: "blake-grupe-ind", rank: 300, name: "Blake Grupe", team: "IND", position: "K", byeWeek: 13, tier: null, adp: null },
    { id: "dolphins-d-st-mia", rank: 301, name: "Dolphins D/ST", team: "MIA", position: "DST", byeWeek: 6, tier: null, adp: null },
    { id: "jason-sanders-nyj", rank: 302, name: "Jason Sanders", team: "NYJ", position: "K", byeWeek: 13, tier: null, adp: null },
    { id: "commanders-d-st-was", rank: 303, name: "Commanders D/ST", team: "WAS", position: "DST", byeWeek: 7, tier: null, adp: null },
    { id: "trey-smack-gb", rank: 304, name: "Trey Smack", team: "GB", position: "K", byeWeek: 11, tier: null, adp: null },
    { id: "jake-moody-was", rank: 305, name: "Jake Moody", team: "WAS", position: "K", byeWeek: 7, tier: null, adp: null },
    { id: "andre-szmyt-cle", rank: 306, name: "Andre Szmyt", team: "CLE", position: "K", byeWeek: 11, tier: null, adp: null },
    { id: "ryan-fitzgerald-car", rank: 307, name: "Ryan Fitzgerald", team: "CAR", position: "K", byeWeek: 5, tier: null, adp: null },
    { id: "chad-ryland-ari", rank: 308, name: "Chad Ryland", team: "ARI", position: "K", byeWeek: 14, tier: null, adp: null },
    { id: "joey-slye-ten", rank: 309, name: "Joey Slye", team: "TEN", position: "K", byeWeek: 9, tier: null, adp: null },
    { id: "chris-brazzell-ii-car", rank: 310, name: "Chris Brazzell II", team: "CAR", position: "WR", byeWeek: 5, tier: 10, adp: null },
    { id: "devaughn-vele-no", rank: 311, name: "Devaughn Vele", team: "NO", position: "WR", byeWeek: 8, tier: 10, adp: null },
    { id: "cooper-kupp-sea", rank: 312, name: "Cooper Kupp", team: "SEA", position: "WR", byeWeek: 11, tier: 10, adp: null },
    { id: "isaac-guerendo-sf", rank: 313, name: "Isaac Guerendo", team: "SF", position: "RB", byeWeek: 8, tier: 12, adp: null },
    { id: "kaelon-black-sf", rank: 314, name: "Kaelon Black", team: "SF", position: "RB", byeWeek: 8, tier: 12, adp: null },
    { id: "seth-mcgowan-ind", rank: 315, name: "Seth McGowan", team: "IND", position: "RB", byeWeek: 13, tier: 12, adp: null },
    { id: "evan-engram-den", rank: 316, name: "Evan Engram", team: "DEN", position: "TE", byeWeek: 10, tier: 9, adp: null },
    { id: "xavier-legette-car", rank: 317, name: "Xavier Legette", team: "CAR", position: "WR", byeWeek: 5, tier: 10, adp: null },
    { id: "colby-parkinson-lar", rank: 318, name: "Colby Parkinson", team: "LAR", position: "TE", byeWeek: 11, tier: 9, adp: null },
    { id: "brandon-aiyuk-sf", rank: 319, name: "Brandon Aiyuk", team: "SF", position: "WR", byeWeek: 8, tier: 10, adp: null },
    { id: "max-klare-lar", rank: 320, name: "Max Klare", team: "LAR", position: "TE", byeWeek: 11, tier: 9, adp: null },
    { id: "kaleb-johnson-pit", rank: 321, name: "Kaleb Johnson", team: "PIT", position: "RB", byeWeek: 9, tier: 12, adp: null },
    { id: "emanuel-wilson-sea", rank: 322, name: "Emanuel Wilson", team: "SEA", position: "RB", byeWeek: 11, tier: 12, adp: null },
    { id: "trey-benson-ari", rank: 323, name: "Trey Benson", team: "ARI", position: "RB", byeWeek: 14, tier: 12, adp: null },
    { id: "andrei-iosivas-cin", rank: 324, name: "Andrei Iosivas", team: "CIN", position: "WR", byeWeek: 6, tier: 10, adp: null },
    { id: "shedeur-sanders-cle", rank: 325, name: "Shedeur Sanders", team: "CLE", position: "QB", byeWeek: 11, tier: 8, adp: null },
    { id: "hollywood-brown-phi", rank: 326, name: "Hollywood Brown", team: "PHI", position: "WR", byeWeek: 10, tier: 10, adp: null },
    { id: "jaylen-wright-mia", rank: 327, name: "Jaylen Wright", team: "MIA", position: "RB", byeWeek: 6, tier: 12, adp: null },
    { id: "deshaun-watson-cle", rank: 328, name: "Deshaun Watson", team: "CLE", position: "QB", byeWeek: 11, tier: 8, adp: null },
    { id: "michael-penix-atl", rank: 329, name: "Michael Penix", team: "ATL", position: "QB", byeWeek: 5, tier: 8, adp: null },
    { id: "eli-raridon-ne", rank: 330, name: "Eli Raridon", team: "NE", position: "TE", byeWeek: 11, tier: 9, adp: null },
    { id: "devin-neal-no", rank: 331, name: "Devin Neal", team: "NO", position: "RB", byeWeek: 8, tier: 12, adp: null },
    { id: "lequint-allen-jax", rank: 332, name: "LeQuint Allen", team: "JAX", position: "RB", byeWeek: 7, tier: 12, adp: null },
    { id: "jake-tonges-sf", rank: 333, name: "Jake Tonges", team: "SF", position: "TE", byeWeek: 8, tier: 9, adp: null },
    { id: "mack-hollins-ne", rank: 334, name: "Mack Hollins", team: "NE", position: "WR", byeWeek: 11, tier: 10, adp: null },
    { id: "charlie-kolar-lac", rank: 335, name: "Charlie Kolar", team: "LAC", position: "TE", byeWeek: 7, tier: 9, adp: null },
    { id: "konata-mumpfield-lar", rank: 336, name: "Konata Mumpfield", team: "LAR", position: "WR", byeWeek: 11, tier: 10, adp: null },
    { id: "keenan-allen-fa", rank: 337, name: "Keenan Allen", team: "FA", position: "WR", byeWeek: 0, tier: 10, adp: null },
    { id: "erick-all-cin", rank: 338, name: "Erick All", team: "CIN", position: "TE", byeWeek: 6, tier: 9, adp: null },
    { id: "olamide-zaccheaus-atl", rank: 339, name: "Olamide Zaccheaus", team: "ATL", position: "WR", byeWeek: 5, tier: 10, adp: null },
    { id: "trevor-etienne-car", rank: 340, name: "Trevor Etienne", team: "CAR", position: "RB", byeWeek: 5, tier: 12, adp: null },
    { id: "tyreek-hill-fa", rank: 341, name: "Tyreek Hill", team: "FA", position: "WR", byeWeek: 0, tier: 10, adp: null },
    { id: "darnell-washington-pit", rank: 342, name: "Darnell Washington", team: "PIT", position: "TE", byeWeek: 9, tier: 9, adp: null },
    { id: "jaylin-lane-was", rank: 343, name: "Jaylin Lane", team: "WAS", position: "WR", byeWeek: 7, tier: 11, adp: null },
    { id: "kirk-cousins-lv", rank: 344, name: "Kirk Cousins", team: "LV", position: "QB", byeWeek: 13, tier: 8, adp: null },
    { id: "carson-beck-ari", rank: 345, name: "Carson Beck", team: "ARI", position: "QB", byeWeek: 14, tier: 9, adp: null },
    { id: "theo-johnson-nyg", rank: 346, name: "Theo Johnson", team: "NYG", position: "TE", byeWeek: 8, tier: 9, adp: null },
    { id: "joshua-palmer-buf", rank: 347, name: "Joshua Palmer", team: "BUF", position: "WR", byeWeek: 5, tier: 11, adp: null },
    { id: "mason-taylor-nyj", rank: 348, name: "Mason Taylor", team: "NYJ", position: "TE", byeWeek: 13, tier: 9, adp: null },
    { id: "anthony-richardson-ind", rank: 349, name: "Anthony Richardson", team: "IND", position: "QB", byeWeek: 13, tier: 9, adp: null },
    { id: "dont-e-thornton-jr-lv", rank: 350, name: "Dont'e Thornton Jr.", team: "LV", position: "WR", byeWeek: 13, tier: 11, adp: null },
    { id: "j-j-mccarthy-min", rank: 351, name: "J.J. McCarthy", team: "MIN", position: "QB", byeWeek: 6, tier: 9, adp: null },
    { id: "michael-mayer-lv", rank: 352, name: "Michael Mayer", team: "LV", position: "TE", byeWeek: 13, tier: 9, adp: null },
    { id: "mac-jones-sf", rank: 353, name: "Mac Jones", team: "SF", position: "QB", byeWeek: 8, tier: 9, adp: null },
    { id: "justin-fields-kc", rank: 354, name: "Justin Fields", team: "KC", position: "QB", byeWeek: 5, tier: 9, adp: null },
    { id: "ty-simpson-lar", rank: 355, name: "Ty Simpson", team: "LAR", position: "QB", byeWeek: 11, tier: 9, adp: null },
    { id: "malik-davis-dal", rank: 356, name: "Malik Davis", team: "DAL", position: "RB", byeWeek: 14, tier: 12, adp: null },
    { id: "elijah-arroyo-sea", rank: 357, name: "Elijah Arroyo", team: "SEA", position: "TE", byeWeek: 11, tier: 9, adp: null },
    { id: "dawson-knox-buf", rank: 358, name: "Dawson Knox", team: "BUF", position: "TE", byeWeek: 5, tier: 9, adp: null },
    { id: "jalen-tolbert-mia", rank: 359, name: "Jalen Tolbert", team: "MIA", position: "WR", byeWeek: 6, tier: 11, adp: null },
    { id: "isaiah-bond-cle", rank: 360, name: "Isaiah Bond", team: "CLE", position: "WR", byeWeek: 11, tier: 11, adp: null },
    { id: "cole-kmet-chi", rank: 361, name: "Cole Kmet", team: "CHI", position: "TE", byeWeek: 7, tier: 9, adp: null },
    { id: "oscar-delp-no", rank: 362, name: "Oscar Delp", team: "NO", position: "TE", byeWeek: 8, tier: 9, adp: null },
    { id: "ja-tavion-sanders-car", rank: 363, name: "Ja'Tavion Sanders", team: "CAR", position: "TE", byeWeek: 5, tier: 9, adp: null },
    { id: "marvin-mims-den", rank: 364, name: "Marvin Mims", team: "DEN", position: "WR", byeWeek: 10, tier: 11, adp: null },
    { id: "treylon-burks-was", rank: 365, name: "Treylon Burks", team: "WAS", position: "WR", byeWeek: 7, tier: 11, adp: null },
    { id: "kendrick-bourne-ari", rank: 366, name: "Kendrick Bourne", team: "ARI", position: "WR", byeWeek: 14, tier: 11, adp: null },
    { id: "noah-gray-kc", rank: 367, name: "Noah Gray", team: "KC", position: "TE", byeWeek: 5, tier: 9, adp: null },
    { id: "zavion-thomas-chi", rank: 368, name: "Zavion Thomas", team: "CHI", position: "WR", byeWeek: 7, tier: 11, adp: null },
    { id: "emari-demercado-kc", rank: 369, name: "Emari Demercado", team: "KC", position: "RB", byeWeek: 5, tier: 12, adp: null },
    { id: "justin-joly-den", rank: 370, name: "Justin Joly", team: "DEN", position: "TE", byeWeek: 10, tier: 10, adp: null },
    { id: "kyle-williams-ne", rank: 371, name: "Kyle Williams", team: "NE", position: "WR", byeWeek: 11, tier: 11, adp: null },
    { id: "brenen-thompson-lac", rank: 372, name: "Brenen Thompson", team: "LAC", position: "WR", byeWeek: 7, tier: 11, adp: null },
    { id: "jerome-ford-was", rank: 373, name: "Jerome Ford", team: "WAS", position: "RB", byeWeek: 7, tier: 12, adp: null },
    { id: "tahj-brooks-cin", rank: 374, name: "Tahj Brooks", team: "CIN", position: "RB", byeWeek: 6, tier: 12, adp: null },
    { id: "drew-allar-pit", rank: 375, name: "Drew Allar", team: "PIT", position: "QB", byeWeek: 9, tier: 10, adp: null },
    { id: "noah-fant-no", rank: 376, name: "Noah Fant", team: "NO", position: "TE", byeWeek: 8, tier: 10, adp: null },
    { id: "jarquez-hunter-lar", rank: 377, name: "Jarquez Hunter", team: "LAR", position: "RB", byeWeek: 11, tier: 12, adp: null },
    { id: "cade-klubnik-nyj", rank: 378, name: "Cade Klubnik", team: "NYJ", position: "QB", byeWeek: 13, tier: 10, adp: null },
    { id: "jaleel-mclaughlin-den", rank: 379, name: "Jaleel McLaughlin", team: "DEN", position: "RB", byeWeek: 10, tier: 13, adp: null },
    { id: "tutu-atwell-mia", rank: 380, name: "Tutu Atwell", team: "MIA", position: "WR", byeWeek: 6, tier: 11, adp: null },
    { id: "audric-estime-no", rank: 381, name: "Audric Estime", team: "NO", position: "RB", byeWeek: 8, tier: 13, adp: null },
    { id: "luke-musgrave-gb", rank: 382, name: "Luke Musgrave", team: "GB", position: "TE", byeWeek: 11, tier: 10, adp: null },
    { id: "will-shipley-phi", rank: 383, name: "Will Shipley", team: "PHI", position: "RB", byeWeek: 10, tier: 13, adp: null },
    { id: "kareem-hunt-fa", rank: 384, name: "Kareem Hunt", team: "FA", position: "RB", byeWeek: 0, tier: 13, adp: null },
    { id: "jameis-winston-nyg", rank: 385, name: "Jameis Winston", team: "NYG", position: "QB", byeWeek: 8, tier: 10, adp: null },
    { id: "tyler-higbee-lar", rank: 386, name: "Tyler Higbee", team: "LAR", position: "TE", byeWeek: 11, tier: 10, adp: null },
    { id: "jordan-whittington-lar", rank: 387, name: "Jordan Whittington", team: "LAR", position: "WR", byeWeek: 11, tier: 12, adp: null },
    { id: "marcus-mariota-was", rank: 388, name: "Marcus Mariota", team: "WAS", position: "QB", byeWeek: 7, tier: 10, adp: null },
    { id: "demario-douglas-ne", rank: 389, name: "DeMario Douglas", team: "NE", position: "WR", byeWeek: 11, tier: 12, adp: null },
    { id: "luke-schoonmaker-dal", rank: 390, name: "Luke Schoonmaker", team: "DAL", position: "TE", byeWeek: 14, tier: 10, adp: null },
    { id: "eli-heidenreich-pit", rank: 391, name: "Eli Heidenreich", team: "PIT", position: "RB", byeWeek: 9, tier: 13, adp: null },
    { id: "jahan-dotson-atl", rank: 392, name: "Jahan Dotson", team: "ATL", position: "WR", byeWeek: 5, tier: 12, adp: null },
    { id: "darren-waller-car", rank: 393, name: "Darren Waller", team: "CAR", position: "TE", byeWeek: 5, tier: 10, adp: null },
    { id: "jawhar-jordan-hou", rank: 394, name: "Jawhar Jordan", team: "HOU", position: "RB", byeWeek: 8, tier: 13, adp: null },
    { id: "savion-williams-gb", rank: 395, name: "Savion Williams", team: "GB", position: "WR", byeWeek: 11, tier: 12, adp: null },
    { id: "xavier-hutchinson-hou", rank: 396, name: "Xavier Hutchinson", team: "HOU", position: "WR", byeWeek: 8, tier: 12, adp: null },
    { id: "kevin-coleman-jr-mia", rank: 397, name: "Kevin Coleman Jr.", team: "MIA", position: "WR", byeWeek: 6, tier: 12, adp: null },
    { id: "kavontae-turpin-dal", rank: 398, name: "KaVontae Turpin", team: "DAL", position: "WR", byeWeek: 14, tier: 12, adp: null },
    { id: "kalif-raymond-chi", rank: 399, name: "Kalif Raymond", team: "CHI", position: "WR", byeWeek: 7, tier: 12, adp: null },
    { id: "joe-flacco-cin", rank: 400, name: "Joe Flacco", team: "CIN", position: "QB", byeWeek: 6, tier: 10, adp: null },
    { id: "nick-westbrook-ikhine-ind", rank: 401, name: "Nick Westbrook-Ikhine", team: "IND", position: "WR", byeWeek: 13, tier: 12, adp: null },
    { id: "ashton-dulin-ind", rank: 402, name: "Ashton Dulin", team: "IND", position: "WR", byeWeek: 13, tier: 12, adp: null },
    { id: "devontez-walker-bal", rank: 403, name: "Devontez Walker", team: "BAL", position: "WR", byeWeek: 13, tier: 12, adp: null },
    { id: "dameon-pierce-phi", rank: 404, name: "Dameon Pierce", team: "PHI", position: "RB", byeWeek: 10, tier: 14, adp: null },
    { id: "roman-wilson-pit", rank: 405, name: "Roman Wilson", team: "PIT", position: "WR", byeWeek: 9, tier: 12, adp: null },
    { id: "dyami-brown-was", rank: 406, name: "Dyami Brown", team: "WAS", position: "WR", byeWeek: 7, tier: 12, adp: null },
    { id: "greg-dortch-det", rank: 407, name: "Greg Dortch", team: "DET", position: "WR", byeWeek: 6, tier: 12, adp: null },
    { id: "demarcus-robinson-sf", rank: 408, name: "Demarcus Robinson", team: "SF", position: "WR", byeWeek: 8, tier: 12, adp: null },
    { id: "theo-wease-jr-mia", rank: 409, name: "Theo Wease Jr.", team: "MIA", position: "WR", byeWeek: 6, tier: 12, adp: null },
    { id: "riley-leonard-ind", rank: 410, name: "Riley Leonard", team: "IND", position: "QB", byeWeek: 13, tier: 11, adp: null },
    { id: "mo-alie-cox-ind", rank: 411, name: "Mo Alie-Cox", team: "IND", position: "TE", byeWeek: 13, tier: 10, adp: null },
    { id: "gardner-minshew-ari", rank: 412, name: "Gardner Minshew", team: "ARI", position: "QB", byeWeek: 14, tier: 11, adp: null },
    { id: "younghoe-koo-fa", rank: 413, name: "Younghoe Koo", team: "FA", position: "K", byeWeek: 0, tier: null, adp: null },
    { id: "ben-sauls-nyg", rank: 414, name: "Ben Sauls", team: "NYG", position: "K", byeWeek: 8, tier: null, adp: null },
    { id: "spencer-shrader-ind", rank: 415, name: "Spencer Shrader", team: "IND", position: "K", byeWeek: 13, tier: null, adp: null },
    { id: "deandre-hopkins-fa", rank: 416, name: "DeAndre Hopkins", team: "FA", position: "WR", byeWeek: 0, tier: 12, adp: null },
    { id: "taysom-hill-fa", rank: 417, name: "Taysom Hill", team: "FA", position: "TE", byeWeek: 0, tier: 10, adp: null },
    { id: "tyrod-taylor-gb", rank: 418, name: "Tyrod Taylor", team: "GB", position: "QB", byeWeek: 11, tier: 11, adp: null },
    { id: "juju-smith-schuster-nyg", rank: 419, name: "JuJu Smith-Schuster", team: "NYG", position: "WR", byeWeek: 8, tier: 12, adp: null },
    { id: "zonovan-knight-ari", rank: 420, name: "Zonovan Knight", team: "ARI", position: "RB", byeWeek: 14, tier: 14, adp: null },
    { id: "raheim-sanders-cle", rank: 421, name: "Raheim Sanders", team: "CLE", position: "RB", byeWeek: 11, tier: 14, adp: null },
    { id: "daniel-carlson-fa", rank: 422, name: "Daniel Carlson", team: "FA", position: "K", byeWeek: 0, tier: null, adp: null },
    { id: "zane-gonzalez-mia", rank: 423, name: "Zane Gonzalez", team: "MIA", position: "K", byeWeek: 6, tier: null, adp: null },
    { id: "mike-meyer-fa", rank: 424, name: "Mike Meyer", team: "FA", position: "K", byeWeek: 0, tier: null, adp: null }
  ];

  DC.data = { TEAM_BYE_WEEKS: TEAM_BYE_WEEKS, SEED_PLAYERS: SEED_PLAYERS, slug: slug };
})();
